version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install -r requirements.txt
      - mkdir /home/wsgi/nltk_data
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - application.py
    - requirements.txt
    - english.pickle
    - averaged_perceptron_tagger.pickle
    - db.sqlite